### ISSUE TITLE
Add support for SSHKey resources

### ISSUE THREAD

**Issue by hqdncw** [hqdncw/vault-autopilot#17]
```yaml
kind: "SecretsEngine"
spec:
  path: "secret"
  engine:
    type: "kv-v2"
---
kind: SSHKey
spec:
  secretsEngine: "secret"
  path: my-perfect-key
  keyOptions:
    type: "rsa"
    bits: 4096
  version: 1
 ```
